### ISSUE TITLE
Add Documentation for Personal Access Token Scope

### ISSUE THREAD

**Issue by greyscaled** [devmasx/coverage-check-action#3]
~Greetings 👋 

Thank you for creating this action, I'm looking forward to integrating it in my workflow(s)!

I wanted to make a small *suggestion* for your documentation.

The `README.md`/documentation for this action references a personal access token:

> ```md
> token: ${{secrets.GITHUB_TOKEN}}
> ```

Additionally, so does the `action.yml`:

https://github.com/devmasx/coverage-check-action/blob/2454e13902d0be70ec54646a8ec5989a03c24a31/action.yml#L13

However, when adding a **P.A.T** there are various scopes that may be granted. As a suggestion, this action could document what **scope(s)** are required. I think the `scope` should be mentioned in both:

- `README.md`
- `action.yml` - `description` for the `token` `input`

I'd happily have issued a PR with this suggestion, but I'm actually not 100% sure what scope *is* required.

Thanks!

✨

**Comment by ekeric13** [comment]
I am also having an issue with not knowing what scopes the github access token should have.

What scopes ended up working for you?

**Comment by greyscaled** [comment]
@ekeric13 I didn't end up using the action as a result, so I do not know :(

**Comment by MiguelSavignano** [comment]
Hello, @vapurrmaid  @ekeric13 

This action requires a Github token with `checks:write` scope to allow create the check run using the [Github API v3](https://developer.github.com/v3/checks/runs/)

But you don't need to set a personal access token, all Github workflow have a GitHub token with this scope.

To avoid confusion, must be update the README replacing `${{secrets.GITHUB_TOKEN}}` with `${{ github.token }}`

Example:
```yaml
- uses: devmasx/coverage-check-action@v1.1.0
  with:
    type: lcov
    result_path: coverage/example.lcov
    min_coverage: 90
    token: ${{ github.token }}
```
